apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: conv-api
  template:
    metadata:
      labels:
        components: conv-api
    spec:
      containers:
        - name: conv-api
          image: antonlarichev/conv-api:1.0
          ports:
            - containerPort: 3000
          env:
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: SEED_USERNAME
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: SEED_USER_PASSWORD
            - name: AMQP_EXCHANGE
              value: test
            - name: AMQP_HOSTNAME
              value: rmq-clusterip
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
          volumeMounts:
            - name: api-data
              mountPath: /opt/app/uploads
      volumes:
        - name: api-data
          persistentVolumeClaim:
            claimName: conv-api-pvc
